name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

env:
  DATABASE_URL: "mysql://placeholder@placeholder/placeholder"
  NEXTAUTH_SECRET: "oooOOOoooh-very-secret"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          ref: ${{ github.head_ref }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Type checking
        run: npm run typecheck

      - name: Lint and format check
        run: npm run lint

      - name: Run Prettier
      - run: npm run format

      - name: Commit Prettier Changes
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier formatting changes