name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

env:
  DATABASE_URL: "mysql://placeholder@placeholder/placeholder"
  NEXTAUTH_SECRET: "oooOOOoooh-very-secret"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality_scan:

    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Type checking
        run: npm run typecheck

      - name: Lint and format check
        run: npm run lint

      - name: Run Prettier
      - run: npm run format:fix

      - name: Commit Prettier Changes
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier formatting changes