name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

env:
  DATABASE_URL: "mysql://placeholder@placeholder/placeholder"
  NEXTAUTH_SECRET: "oooOOOoooh-very-secret"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Type checking
        run: npm run typecheck

      - name: Lint and format check
        run: npm run lint

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          only_changed: True
          dry: True